name: build wiki

on: [pull_request]

jobs:
  build-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: install dep
        run: yarn install
      
      - name: build wiki
        run : yarn run docs:build
